export const homeObjOne = {
  id: "about",
  lightBg: true,
  lightText: false,
  topLineColor: false,
  lightTextDesc: false,
  topLine: "01. About Me",
  headLine: "filler text more filler",
  description: "subtitle filler text",
  imgStart: true,
  img: require("../../images/photo-6.jpg"),
  alt: "error404",
  dark: false,
  primary: false,
  darkText: true,
  textAlign: false,
  buttonAlign: true,
};

export const homeObjTwo = {
  id: "skills",
  lightBg: false,
  lightText: true,
  topLineColor: true,
  lightTextDesc: true,
  topLine: "02. Skills",
  headLine: "Here are all the technologies and languages I've worked with",
  description: "subtitle filler text",
  dark: true,
  primary: true,
  darkText: false,
  textAlign: true,
  buttonAlign: false,
};

export const homeObjThree = {
  id: "projects",
  lightBg: true,
  lightText: false,
  topLineColor: false,
  lightTextDesc: false,
  topLine: "03. Experience and Projects",
  headLine: "What have I built?",
  description: "subtitle filler text",
  dark: false,
  primary: false,
  darkText: true,
  textAlign: true,
  buttonAlign: true,
};

export const homeObjFour = {
  id: "contact",
  lightBg: false,
  lightText: true,
  topLineColor: true,
  lightTextDesc: true,
  topLine: "04. Contact",
  headLine: "Want to get in touch?",
  description:
    "You can reach out to me either on my socials below or through email by clicking on the button. My inbox is always open, and I'll get back to you as soon as I can!",
  buttonLabel: "Say Hello",
  dark: true,
  primary: true,
  darkText: false,
  textAlign: true,
  buttonAlign: false,
};
